# Generated by Django 3.0.2 on 2020-01-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logoUri', models.ImageField(upload_to='team/logo_uri/%Y/%m/%d')),
                ('club_state', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
