# Generated by Django 3.0.2 on 2020-01-11 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
