# Generated by Django 3.0.2 on 2020-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_app', '0003_auto_20200111_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='teams',
            field=models.ManyToManyField(to='cricket_app.Team'),
        ),
    ]
