# Generated by Django 3.0.2 on 2020-01-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_app', '0004_fixture_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='score_team1',
        ),
        migrations.RemoveField(
            model_name='point',
            name='score_team2',
        ),
        migrations.AddField(
            model_name='point',
            name='fixture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket_app.Fixture'),
        ),
        migrations.AddField(
            model_name='point',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket_app.Team'),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='run',
            field=models.IntegerField(default=0),
        ),
    ]
